apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # 🔥 argocdName
  name: baseinfo-app-of-apps
  # ArgoCD가 설치되어 있는 namespace
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: mvp
  
  source:
    # 🔥 repoURL
    repoURL: https://github.com/cloudnative-mvp1/mvp_baseinfo_backend_gitops.git
    targetRevision: HEAD
    path: charts/backend
  
  destination:
    server: https://kubernetes.default.svc
    # 🔥 namespace
    namespace: mvp
    
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=false   
